## Goal definition
DoFConfiguration[] configuration
uint16 time
---
## Result definition
DoFConfiguration[] resultConfiguration
---
## Feedback definition
DoFConfiguration[] interimConfiguration
bool moving